# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

configfile: "config/config.yaml"
include: "rules/common.py"


include: "rules/ds-dge.smk"
include: "rules/eqtl.smk"
include: "rules/sqtl.smk"
include: "rules/coloc.smk"
include: "rules/PrepareGWAS.smk"
include: "rules/Sashimi.smk"
include: "rules/TCGA.smk"
include: "rules/BFS_comparisons.smk"

# Upstream rules from the SpliFi project, reproduced verbatim but COMMENTED OUT.
# They document where the GTEx splicing/expression phenotypes and genotypes that
# this workflow reads by absolute path actually came from, and would let the
# chain be re-run here. Uncomment this include AND the rules in that file, and
# switch the commented local `input:` lines in coloc/sqtl/eqtl/ds-dge/Sashimi.
# include: "rules/SpliFi_upstream.smk"

localrules:
    all,
    InstallHyprcoloc,

rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.




include: "rules/other.smk"
